apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  # Database configuration
  MYSQL_HOST: "mysql" # The name of the MySQL service
  MYSQL_DATABASE: "e_commerce"

  # Eureka configuration
  EUREKA_HOST: "eureka-service" # The name of the Eureka service
  EUREKA_PORT: "8761"