
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  clusterIP: None # 1. Converted to a Headless Service
  ports:
    - port: 3306
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: StatefulSet # 2. Changed from Deployment to StatefulSet
metadata:
  name: mysql
spec:
  serviceName: "mysql" # 3. Added governing service name
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:latest
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
  # 4. Replaced the standalone PVC and Deployment Volumes block with volumeClaimTemplates
  volumeClaimTemplates:
    - metadata:
        name: mysql-persistent-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 20Gi