server:  
  port: 8086  

spring:  
  application:  
    name: notification-service-api

  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT:3306}/${MYSQL_DATABASE}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:  
    hibernate:  
      ddl-auto: update  
    show-sql: true  

  mail:  
    host: smtp.gmail.com  
    port: 587  
    username: 
    password: 
    properties:  
      mail:  
        smtp:  
          auth: true  
          starttls:  
            enable: true
            
twilio:  
  account-sid: 
  auth-token: 
  from-number: 

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT}/eureka
